# Generated by Django 5.1.6 on 2025-02-09 22:09

import django.db.models.deletion
import django.utils.timezone
import invoices.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المؤسسة')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المتجر')),
                ('vat_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='الرقم الضريبي')),
                ('cr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=4, verbose_name='نسبة الضريبة (%)')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركات',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('vat_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='الرقم الضريبي')),
            ],
            options={
                'verbose_name': 'العميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, unique=True, verbose_name='الاسم العربي')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الاسم الإنجليزي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الصنف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'صنف المنتج',
                'verbose_name_plural': 'أصناف المنتجات',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الوحدة الأساسية')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='التمييز')),
                ('template', models.CharField(help_text='مثال: الوزن', max_length=50, verbose_name='القالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('sales', 'فاتورة مبيعات'), ('purchase', 'فاتورة مشتريات')], default='sales', max_length=20, verbose_name='نوع الفاتورة')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الفاتورة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('subtotal_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي قبل الخصم')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('subtotal_before_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المجموع قبل الضريبة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الصافي')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='كود QR')),
                ('company', models.ForeignKey(default=invoices.models.get_default_company, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.companysettings', verbose_name='الشركة')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.customer', verbose_name='العميل')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.paymentmethod', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم المنتج بالعربي')),
                ('name_en', models.CharField(max_length=255, verbose_name='اسم المنتج بالإنجليزي')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='حد التنبيه')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoices.productcategory', verbose_name='الصنف')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.unit', verbose_name='وحدة القياس')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('larger_unit_name', models.CharField(max_length=100, verbose_name='اسم الوحدة الأكبر')),
                ('larger_unit_abbreviation', models.CharField(max_length=20, verbose_name='التمييز')),
                ('conversion_factor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='معامل التحويل')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='invoices.unit', verbose_name='الوحدة الأساسية')),
            ],
            options={
                'verbose_name': 'تحويل وحدة',
                'verbose_name_plural': 'تحويلات الوحدات',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر لكل وحدة')),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='المجموع قبل الضريبة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='نسبة الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='المجموع النهائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.product', verbose_name='المنتج')),
                ('base_unit', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='invoices.unit', verbose_name='الوحدة الأساسية')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.unitconversion', verbose_name='الوحدة المختارة')),
            ],
            options={
                'verbose_name': 'عنصر الفاتورة',
                'verbose_name_plural': 'عناصر الفاتورة',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_in_invoice_e6b546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoices_in_invoice_087f87_idx'),
        ),
    ]
