# Generated by Django 5.1.6 on 2025-02-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'إعدادات المنشأة', 'verbose_name_plural': 'إعدادات المنشآت'},
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='name',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='store_name',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان (سطر 1)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان (سطر 2)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الفرع أو الورشة'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='country',
            field=models.CharField(blank=True, default='المملكة العربية السعودية', max_length=100, null=True, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='legal_name',
            field=models.CharField(default=4, max_length=255, verbose_name='الاسم القانوني للمنشأة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار المنشأة'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='postal_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='الرمز البريدي'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة / المحافظة'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='trading_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم التجاري'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
    ]
