# Generated by Django 5.1.6 on 2025-02-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_companysettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المورد')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم جهة الاتصال (الشخص المسؤول)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف / الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الشارع 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الشارع 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة / المحافظة')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('country', models.CharField(blank=True, default='المملكة العربية السعودية', max_length=100, null=True, verbose_name='البلد')),
                ('vat_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='الرقم الضريبي (إن وجد)')),
                ('cr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري (إن وجد)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'عميل', 'verbose_name_plural': 'عملاء'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الشارع 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الشارع 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الشخص المسؤول (إن وجد)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, default='المملكة العربية السعودية', max_length=100, null=True, verbose_name='البلد'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي'),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة / المحافظة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف / الجوال'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='الرقم الضريبي (إن وجد)'),
        ),
    ]
