# Generated by Django 5.1.6 on 2025-02-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_supplier_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cr_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري (إن وجد)'),
        ),
    ]
