# Generated by Django 5.1.6 on 2025-02-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_customer_cr_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysettings',
            old_name='trading_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='branch_name',
        ),
    ]
