# Generated by Django 5.1.6 on 2025-02-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_rename_trading_name_companysettings_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('sales', 'فاتورة مبيعات'), ('sales_return', 'مرتجع مبيعات'), ('purchase', 'فاتورة مشتريات'), ('purchase_return', 'مرتجع مشتريات')], default='sales', max_length=20, verbose_name='نوع الفاتورة'),
        ),
    ]
