# Generated by Django 5.1.6 on 2025-02-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_supplier_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='en_legal_name',
            field=models.CharField(default=6, max_length=255, verbose_name='  انجليزي الاسم القانوني للمنشأة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysettings',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم التجاري بالإنجليزي'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' الاسم التجاري عربي'),
        ),
    ]
