# Generated by Django 5.1.6 on 2025-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_companysettings_en_legal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='return_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب المرتجع'),
        ),
    ]
