# Generated by Django 5.1.6 on 2025-02-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='return_reason',
            field=models.TextField(blank=True, default='', null=True, verbose_name='سبب المرتجع'),
        ),
    ]
