# Generated by Django 5.1.6 on 2025-02-17 00:57

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_invoice_return_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='region',
        ),
        migrations.AddField(
            model_name='invoice',
            name='nvoice_number',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='رقم الفاتورة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, help_text='لفواتير المرتجعات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='invoices.invoice', verbose_name='الفاتورة الأصلية'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي'),
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الحساب')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('income', 'إيرادات'), ('expense', 'مصروفات')], max_length=50, verbose_name='نوع الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الرصيد')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='invoices.chartofaccount', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'شجرة الحسابات',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_accounts', to='invoices.chartofaccount', verbose_name='حساب العميل'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_products', to='invoices.chartofaccount', verbose_name='حساب المخزون'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_accounts', to='invoices.chartofaccount', verbose_name='حساب المورد'),
        ),
    ]
