# Generated by Django 5.1.6 on 2025-02-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_remove_companysettings_address_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='nvoice_number',
        ),
    ]
