# Generated by Django 5.1.6 on 2025-02-18 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_remove_invoice_nvoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='return_reason',
            field=models.TextField(blank=True, default='0', null=True, verbose_name='سبب المرتجع'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='base_unit',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.unit', verbose_name='الوحدة الأساسية'),
        ),
    ]
