# Generated by Django 5.1.6 on 2025-02-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_alter_invoice_return_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='الرقم التسلسلي'),
            preserve_default=False,
        ),
    ]
