# Generated by Django 5.1.6 on 2025-02-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_remove_product_name_en_product_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_line1',
            new_name='address_line',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='address_line1',
            new_name='address_line',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='region',
        ),
    ]
