# Generated by Django 5.1.6 on 2025-02-18 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_rename_address_line1_customer_address_line_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysettings',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='en_legal_name',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='legal_name',
        ),
    ]
