# Generated by Django 5.1.6 on 2025-02-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_in_invoice_e6b546_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_in_invoice_087f87_idx',
        ),
    ]
