# Generated by Django 5.1.6 on 2025-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الفاكس'),
        ),
    ]
