# Generated by Django 5.1.6 on 2025-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_customer_fax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fax',
        ),
        migrations.AddField(
            model_name='supplier',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الفاكس'),
        ),
    ]
