# Generated by Django 5.1.6 on 2025-02-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_remove_customer_fax_supplier_fax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='fax',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الفاكس'),
        ),
    ]
