# Generated by Django 5.1.6 on 2025-02-20 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الوحدة الأساسية')),
                ('name_en', models.CharField(max_length=50, unique=True, verbose_name='انجليزي اسم الوحدة')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='الرمز')),
                ('template', models.CharField(help_text='مثال: الوزن', max_length=50, verbose_name='القالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='عامل التحويل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_conversions', to='inventory.unit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_conversions', to='inventory.unit')),
            ],
            options={
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
